#!/usr/bin/env python3
"""Paired transfer test of the pre012 stack view on the pyramid-minimal head.

The stack-mask graduation proved pre012 on the TCN concat head; the Phase-8
chain builds on ``gated_pyramid_ordinal`` from arm ``a0`` upward.  This runner
asks whether the view transfers to the pyramid fusion BEFORE the chain root is
sealed.  It never runs, reconfigures, or seals the Phase-8 chain: arm configs
are generated by the chain's own ``base_config()``/``finalize_training_block``
so the ``all6`` control is byte-identical to the chain's ``a0`` arm except for
``training.log_dir`` (and, in the treatment arm, ``stack_input_mask``).

Commands: ``preflight`` / ``run`` / ``report``.  Training occurs only for the
explicit ``run`` command.  See ``PYRAMID_MASK_TRANSFER_PREREG.md`` for the
locked protocol and decision rules.
"""

from __future__ import annotations

import argparse
import copy
import datetime as dt
import fcntl
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Mapping, Tuple

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO))

import phase8_chain_driver as chain  # noqa: E402
from run_stack_mask_graduation import (  # noqa: E402
    atomic_json,
    atomic_text,
    canonical_json,
    canonical_yaml,
    config_sha,
    disk_preflight,
    fail,
    gpu_preflight,
    load_exact_v3_backbone,
    parameter_schema,
    reset_initialization_rng,
    sha_file,
    state_schema,
    tensor_digest,
    unique_stale_path,
)

PY = Path(chain.PY)
INIT = REPO / chain.INIT
VOX_SEL = Path(chain.VOX_SEL)
PREREG = REPO / "PYRAMID_MASK_TRANSFER_PREREG.md"
ART = REPO / "artifacts/pyramid_mask_transfer"
RESULTS = REPO / "results"
LOGS = REPO / "logs"

SEEDS = (1234, 2345, 3456)
STEPS = chain.STEPS
NONINF_MARGIN = -0.002
N_BOOT = 20_000
BOOT_SEED = 0

STACK_DIMS = (192, 256, 384, 512, 384, 256)
PRE012 = (1, 1, 1, 0, 0, 0)
# all6 carries NO stack_input_mask key: it must stay byte-identical to the
# chain's a0 config (modulo training.log_dir), not merely numerically equal.
ARMS: Mapping[str, Tuple[int, ...] | None] = {
    "all6": None,
    "pre012": PRE012,
}
RUN_ORDER = (
    (1234, "all6"), (1234, "pre012"),
    (2345, "pre012"), (2345, "all6"),
    (3456, "all6"), (3456, "pre012"),
)
ROOT_TAG = "p8a_average"  # immutable TCN root, descriptive contrast only

ZIPFORMER_DIR = "third_party/icefall/egs/librispeech/ASR/zipformer"
SOURCE_FILES = (
    "scripts/run_pyramid_mask_transfer.py",
    "scripts/run_stack_mask_graduation.py",
    "scripts/phase8_chain_driver.py",
    "PYRAMID_MASK_TRANSFER_PREREG.md",
    "configs/zipcount_v4_distill.yaml",
    "configs/zipcount_pyramid_ordinal.yaml",
    "src/train.py",
    "src/models/zipcount_v1.py",
    "src/models/zipformer_wrapper.py",
    "src/models/heads.py",
    "src/models/deformable.py",
    "src/models/pyramid_head.py",
    "src/models/losses.py",
    "src/models/structured_losses.py",
    "src/models/crnn_baseline.py",
    "src/data/dataset.py",
    "src/data/label_utils.py",
    "src/data/feature_extractor.py",
    "src/utils/metrics.py",
    "scripts/eval_per_recording.py",
    f"{ZIPFORMER_DIR}/zipformer.py",
    f"{ZIPFORMER_DIR}/scaling.py",
    f"{ZIPFORMER_DIR}/subsampling.py",
    f"{ZIPFORMER_DIR}/model.py",
    f"{ZIPFORMER_DIR}/finetune.py",
    f"{ZIPFORMER_DIR}/encoder_interface.py",
    f"{ZIPFORMER_DIR}/decoder.py",
    f"{ZIPFORMER_DIR}/joiner.py",
    f"{ZIPFORMER_DIR}/optim.py",
    f"{ZIPFORMER_DIR}/asr_datamodule.py",
)


def source_snapshot() -> Dict[str, Any]:
    import hashlib

    files = {rel: sha_file(REPO / rel) for rel in SOURCE_FILES}
    return {
        "files": files,
        "combined_sha": hashlib.sha256(canonical_json(files)).hexdigest(),
    }


def assert_source_snapshot(expected: Mapping[str, Any], where: str) -> None:
    live = source_snapshot()
    if live != expected:
        changed = sorted(
            rel for rel in set(expected.get("files", {})) | set(live["files"])
            if expected.get("files", {}).get(rel) != live["files"].get(rel)
        )
        fail(
            f"source freeze violated {where}; changed={changed}. "
            "The in-flight run is uncertified."
        )


def tag(arm: str, seed: int) -> str:
    if arm not in ARMS or seed not in SEEDS:
        fail(f"invalid arm/seed: {arm}/{seed}")
    return f"pyrmask_{arm}_s{seed}"


def paths_for(arm: str, seed: int) -> Dict[str, Path]:
    name = tag(arm, seed)
    return {
        "config": ART / f"{name}.yaml",
        "sidecar": ART / f"{name}.lineage.json",
        "result": RESULTS / f"{name}_voxsel.json",
        "checkpoint": LOGS / name / f"step{STEPS}.pt",
        "log_dir": LOGS / name,
        "log": LOGS / f"{name}.log",
    }


def make_config(arm: str, seed: int) -> Dict[str, Any]:
    if arm not in ARMS:
        fail(f"unknown arm: {arm}")
    config = chain.base_config()
    mask = ARMS[arm]
    if mask is not None:
        config["model"]["head"]["stack_input_mask"] = list(mask)
    chain.finalize_training_block(config, seed, tag(arm, seed))
    return config


def protocol_inputs(
    config: Mapping[str, Any], snapshot: Mapping[str, Any]
) -> Dict[str, Any]:
    data = config["data"]
    encoder = config["model"]["encoder"]
    return {
        "config_sha": config_sha(config),
        "init_sha": sha_file(INIT),
        "train_manifest_sha": sha_file(Path(data["train_manifest"])),
        "val_manifest_sha": sha_file(Path(data["val_manifest"])),
        "eval_manifest_sha": sha_file(VOX_SEL),
        "stats_sha": sha_file(Path(data["stats_file"])),
        "encoder_pretrained_sha": sha_file(Path(encoder["checkpoint"])),
        "source_combined_sha": snapshot["combined_sha"],
        "source_files": snapshot["files"],
        "locked_step": STEPS,
    }


def output_fingerprint(arm: str, seed: int) -> Dict[str, Any]:
    p = paths_for(arm, seed)
    with p["config"].open() as stream:
        disk_config = yaml.safe_load(stream)
    with p["result"].open() as stream:
        result = json.load(stream)
    if result.get("manifest") != str(VOX_SEL):
        fail(f"{tag(arm, seed)} result names the wrong evaluation manifest")
    if int(result.get("n_recordings", -1)) <= 0:
        fail(f"{tag(arm, seed)} result contains no recordings")
    if result.get("checkpoint") not in {
        str(p["checkpoint"].relative_to(REPO)), str(p["checkpoint"])
    }:
        fail(f"{tag(arm, seed)} result names the wrong checkpoint")
    return {
        "config_sha": config_sha(disk_config),
        "config_file_sha": sha_file(p["config"]),
        "checkpoint_sha": sha_file(p["checkpoint"]),
        "result_sha": sha_file(p["result"]),
        "n_recordings": int(result["n_recordings"]),
    }


def lineage_valid(
    arm: str, seed: int, wanted_yaml: str, wanted_inputs: Mapping[str, Any]
) -> bool:
    p = paths_for(arm, seed)
    required = ("config", "sidecar", "result", "checkpoint")
    if not all(p[key].is_file() and p[key].stat().st_size > 0
               for key in required):
        return False
    try:
        if p["config"].read_text() != wanted_yaml:
            return False
        with p["sidecar"].open() as stream:
            stored = json.load(stream)
        if stored.get("inputs") != wanted_inputs:
            return False
        return stored.get("outputs") == output_fingerprint(arm, seed)
    except (
        SystemExit, OSError, ValueError, KeyError, TypeError,
        json.JSONDecodeError,
    ):
        return False


def invalidate(arm: str, seed: int, reason: str) -> None:
    stamp = dt.datetime.now().strftime("%Y%m%dT%H%M%S")
    p = paths_for(arm, seed)
    moved = []
    for key in ("result", "config", "sidecar", "log", "log_dir"):
        path = p[key]
        if path.exists():
            destination = unique_stale_path(path, stamp)
            path.rename(destination)
            moved.append(str(destination.relative_to(REPO)))
    if moved:
        print(f"[stale] {tag(arm, seed)}: {reason}: {moved}", flush=True)


def arm_has_any_artifact(arm: str, seed: int) -> bool:
    return any(path.exists() for path in paths_for(arm, seed).values())


def remove_intermediate_checkpoints(log_dir: Path) -> None:
    locked = log_dir / f"step{STEPS}.pt"
    if not locked.is_file() or locked.stat().st_size == 0:
        fail(f"locked checkpoint absent: {locked}")
    for path in log_dir.glob("step*.pt"):
        if path != locked:
            path.unlink()


# --------------------------------------------------------------------------
# preflight
# --------------------------------------------------------------------------

def _output_tensors(head: Any, value: Any) -> List[Tuple[str, Any]]:
    import torch

    output = head(value)
    return [
        (name, field)
        for name, field in zip(output._fields, output)
        if isinstance(field, torch.Tensor)
    ]


def check_mask_semantics(models: Mapping[str, Any], seed: int) -> None:
    import torch

    offsets = np.cumsum((0,) + STACK_DIMS)
    generator = torch.Generator().manual_seed(seed + 90_000)
    base = torch.randn(2, 11, sum(STACK_DIMS), generator=generator)
    perturb = torch.randn(2, 11, sum(STACK_DIMS), generator=generator)
    for arm, model in models.items():
        head = model.head.eval()
        mask = ARMS[arm] or (1,) * len(STACK_DIMS)
        included = base.clone()
        excluded = base.clone()
        poisoned = base.clone()
        for index, enabled in enumerate(mask):
            start, end = int(offsets[index]), int(offsets[index + 1])
            if enabled:
                included[..., start:end] += perturb[..., start:end]
            else:
                excluded[..., start:end] += perturb[..., start:end]
                poisoned[..., start:end] = float("nan")
        with torch.no_grad():
            reference = _output_tensors(head, base)
            included_out = _output_tensors(head, included)
            excluded_out = _output_tensors(head, excluded)
            poisoned_out = _output_tensors(head, poisoned)
        included_delta = max(
            (b - a).abs().max().item()
            for (_, a), (_, b) in zip(reference, included_out)
        )
        if included_delta <= 1e-7:
            fail(f"{arm}/seed{seed}: included stacks do not affect output")
        if 0 in mask:
            for (name, a), (_, b), (_, c) in zip(
                reference, excluded_out, poisoned_out
            ):
                if not torch.equal(a, b):
                    fail(
                        f"{arm}/seed{seed}: excluded stacks leak into "
                        f"{name} (max delta "
                        f"{(b - a).abs().max().item():.3e})"
                    )
                if not torch.equal(a, c) or not torch.isfinite(c).all():
                    fail(
                        f"{arm}/seed{seed}: non-finite masked stacks poison "
                        f"{name}"
                    )


def model_equivalence_preflight() -> Dict[str, Any]:
    """Prove both arms share the graph and exact post-init tensor values."""
    import torch

    from src.models.zipcount_v1 import build_model

    summary: Dict[str, Any] = {}
    for seed in SEEDS:
        models: Dict[str, Any] = {}
        rows: Dict[str, Any] = {}
        for arm in ARMS:
            config = make_config(arm, seed)
            reset_initialization_rng(seed)
            model = build_model(copy.deepcopy(config)).cpu()
            missing, unexpected = load_exact_v3_backbone(model)
            for parameter in model.backbone.parameters():
                parameter.requires_grad = False
            models[arm] = model
            rows[arm] = {
                "state_schema": state_schema(model),
                "parameter_schema": parameter_schema(model),
                "state_sha": tensor_digest(model.state_dict().items()),
                "parameter_init_sha": tensor_digest(model.named_parameters()),
                "head_init_sha": tensor_digest(model.head.named_parameters()),
                "total_params": sum(p.numel() for p in model.parameters()),
                "trainable_params": sum(
                    p.numel() for p in model.parameters() if p.requires_grad
                ),
                "missing_after_v3_backbone": missing,
                "unexpected_after_v3_backbone": unexpected,
            }
        reference = rows["all6"]
        invariant_keys = (
            "state_schema", "parameter_schema", "state_sha",
            "parameter_init_sha", "head_init_sha", "total_params",
            "trainable_params", "missing_after_v3_backbone",
            "unexpected_after_v3_backbone",
        )
        for arm, row in rows.items():
            for key in invariant_keys:
                if row[key] != reference[key]:
                    fail(
                        f"matched-init preflight failed for seed {seed}, "
                        f"{arm}: {key} differs from all6"
                    )
        check_mask_semantics(models, seed)
        summary[str(seed)] = {
            key: reference[key]
            for key in (
                "state_sha", "parameter_init_sha", "head_init_sha",
                "total_params", "trainable_params",
                "missing_after_v3_backbone", "unexpected_after_v3_backbone",
            )
        }
        del models
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    return summary


def validate_static_protocol(snapshot: Mapping[str, Any]) -> Dict[str, Any]:
    if not PY.is_file():
        fail(f"Python environment not found: {PY}")
    for path in (INIT, VOX_SEL, PREREG):
        sha_file(path)
    if RUN_ORDER != (
        (1234, "all6"), (1234, "pre012"),
        (2345, "pre012"), (2345, "all6"),
        (3456, "all6"), (3456, "pre012"),
    ):
        fail("locked run order changed")
    for seed in SEEDS:
        configs = {arm: make_config(arm, seed) for arm in ARMS}
        head = configs["all6"]["model"]["head"]
        if (
            head.get("type") != "gated_pyramid_ordinal"
            or head.get("gate_mode") != "global"
            or head.get("ordinal_mode") != "softmax"
            or head.get("use_stage2") is not False
            or "stack_input_mask" in head
        ):
            fail(f"all6/seed{seed}: not the chain's pyramid-minimal a0 head")
        encoder = configs["all6"]["model"]["encoder"]
        if (
            encoder.get("multiscale_alignment") != "average"
            or encoder.get("multiscale_include_final") is not False
        ):
            fail(f"all6/seed{seed}: encoder view differs from the chain base")
        reference = copy.deepcopy(configs["all6"])
        reference["training"].pop("log_dir")
        candidate = copy.deepcopy(configs["pre012"])
        mask = tuple(candidate["model"]["head"].pop("stack_input_mask"))
        candidate["training"].pop("log_dir")
        if mask != PRE012:
            fail(f"pre012/seed{seed}: wrong stack_input_mask {mask}")
        if candidate != reference:
            fail(f"pre012/seed{seed}: config differs beyond stack_input_mask")
        for path in (
            Path(configs["all6"]["data"]["train_manifest"]),
            Path(configs["all6"]["data"]["val_manifest"]),
            Path(configs["all6"]["data"]["stats_file"]),
            Path(configs["all6"]["model"]["encoder"]["checkpoint"]),
        ):
            sha_file(path)
    for seed in SEEDS:
        root = RESULTS / f"{ROOT_TAG}_s{seed}_voxsel.json"
        sha_file(root)
    assert_source_snapshot(snapshot, "during static preflight")
    summary = model_equivalence_preflight()
    assert_source_snapshot(snapshot, "after matched-model preflight")
    return summary


def current_protocol_record(
    snapshot: Mapping[str, Any], preflight_summary: Mapping[str, Any]
) -> Dict[str, Any]:
    return {
        "protocol": "pyramid-mask-transfer-v1",
        "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source_snapshot": snapshot,
        "preflight": preflight_summary,
        "seeds": list(SEEDS),
        "arms": {
            arm: (list(mask) if mask is not None else None)
            for arm, mask in ARMS.items()
        },
        "steps": STEPS,
        "run_order": [list(item) for item in RUN_ORDER],
    }


def install_protocol_record(record: Mapping[str, Any]) -> None:
    path = ART / "protocol_snapshot.json"
    if path.exists():
        try:
            with path.open() as stream:
                old = json.load(stream)
        except (OSError, json.JSONDecodeError):
            old = None
        comparable_old = copy.deepcopy(old)
        comparable_new = json.loads(canonical_json(record))
        if isinstance(comparable_old, dict):
            comparable_old.pop("created_at", None)
        comparable_new.pop("created_at", None)
        if comparable_old == comparable_new:
            return
        destination = unique_stale_path(
            path, dt.datetime.now().strftime("%Y%m%dT%H%M%S")
        )
        path.rename(destination)
        print(f"[stale] protocol snapshot -> {destination.relative_to(REPO)}")
    atomic_json(path, record)


# --------------------------------------------------------------------------
# execution
# --------------------------------------------------------------------------

def run_one(arm: str, seed: int, snapshot: Mapping[str, Any]) -> Path:
    name = tag(arm, seed)
    p = paths_for(arm, seed)
    config = make_config(arm, seed)
    wanted_yaml = canonical_yaml(config)
    wanted_inputs = protocol_inputs(config, snapshot)

    if lineage_valid(arm, seed, wanted_yaml, wanted_inputs):
        print(f"[skip] {name}: input/output lineage verified", flush=True)
        return p["result"]
    if arm_has_any_artifact(arm, seed):
        invalidate(arm, seed, "incomplete or lineage drift")

    assert_source_snapshot(snapshot, f"before {name}")
    disk_preflight()
    atomic_text(p["config"], wanted_yaml)
    with p["config"].open() as stream:
        disk_config = yaml.safe_load(stream)
    if disk_config != config or config_sha(disk_config) != wanted_inputs["config_sha"]:
        fail(f"{name}: on-disk config differs from the preflighted config")

    print(
        f"[run ] {name} config={wanted_inputs['config_sha'][:12]} "
        f"source={wanted_inputs['source_combined_sha'][:12]}",
        flush=True,
    )
    start = time.time()
    with p["log"].open("w") as log:
        subprocess.run(
            [
                str(PY), "src/train.py", "--config", str(p["config"]),
                "--init-from", str(INIT),
            ],
            cwd=REPO,
            env={**os.environ, "PYTHONPATH": "."},
            stdout=log,
            stderr=subprocess.STDOUT,
            check=True,
        )
    if not p["checkpoint"].is_file() or p["checkpoint"].stat().st_size == 0:
        fail(f"{name}: training finished without locked step-{STEPS} checkpoint")

    subprocess.run(
        [
            str(PY), "scripts/eval_per_recording.py",
            "--manifest", str(VOX_SEL),
            "--checkpoint", str(p["checkpoint"].relative_to(REPO)),
            "--config", str(p["config"].relative_to(REPO)),
            "--out", str(p["result"].relative_to(REPO)),
        ],
        cwd=REPO,
        env={**os.environ, "PYTHONPATH": "."},
        check=True,
    )

    assert_source_snapshot(snapshot, f"after {name}")
    with p["config"].open() as stream:
        disk_config = yaml.safe_load(stream)
    inputs_after = protocol_inputs(disk_config, snapshot)
    if inputs_after != wanted_inputs or p["config"].read_text() != wanted_yaml:
        fail(f"{name}: protocol/config changed during the run; uncertified")

    outputs = output_fingerprint(arm, seed)
    if outputs["config_sha"] != wanted_inputs["config_sha"]:
        fail(f"{name}: output config is not the input config")
    atomic_json(
        p["sidecar"],
        {
            "completed_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "inputs": wanted_inputs,
            "outputs": outputs,
        },
    )
    remove_intermediate_checkpoints(p["log_dir"])
    print(f"[done] {name} in {(time.time() - start) / 60:.1f} min", flush=True)
    return p["result"]


# --------------------------------------------------------------------------
# statistics and report
# --------------------------------------------------------------------------

def load_result_rows(paths: List[Path]) -> List[Dict[str, Any]]:
    rows = []
    for path in paths:
        if not path.is_file() or path.stat().st_size == 0:
            fail(f"missing result for report: {path}")
        with path.open() as stream:
            rows.append(json.load(stream))
    return rows


def paired_stats(
    control: str,
    treatment: str,
    a_runs: List[Dict[str, Any]],
    b_runs: List[Dict[str, Any]],
) -> Dict[str, Any]:
    all_runs = a_runs + b_runs
    recording_sets = [frozenset(row["per_recording"]) for row in all_runs]
    if len(set(recording_sets)) != 1:
        fail(
            f"{treatment} vs {control}: recording sets differ; paired "
            "intersection is forbidden"
        )
    recordings = sorted(recording_sets[0])
    if not recordings:
        fail(f"{treatment} vs {control}: no recordings")

    per_seed = [
        float(b["pooled"]["macro_f1"] - a["pooled"]["macro_f1"])
        for a, b in zip(a_runs, b_runs)
    ]
    delta_f1_2 = float(np.mean([
        b["pooled"]["f1_2"] - a["pooled"]["f1_2"]
        for a, b in zip(a_runs, b_runs)
    ]))
    delta_osd = float(np.mean([
        b["pooled"]["osd_f1"] - a["pooled"]["osd_f1"]
        for a, b in zip(a_runs, b_runs)
    ]))
    rec_a = np.asarray([
        [row["per_recording"][recording]["macro_f1"]
         for recording in recordings]
        for row in a_runs
    ]).mean(axis=0)
    rec_b = np.asarray([
        [row["per_recording"][recording]["macro_f1"]
         for recording in recordings]
        for row in b_runs
    ]).mean(axis=0)
    per_recording_delta = rec_b - rec_a
    rng = np.random.default_rng(BOOT_SEED)
    boot = per_recording_delta[
        rng.integers(0, len(recordings), size=(N_BOOT, len(recordings)))
    ].mean(axis=1)
    ci = [float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))]
    mean_pooled = float(np.mean(per_seed))
    practical_r2 = mean_pooled >= 0.005
    practical_r3 = (
        (delta_f1_2 >= 0.010 or delta_osd >= 0.010)
        and mean_pooled >= NONINF_MARGIN
    )
    operational_ni = mean_pooled >= NONINF_MARGIN
    strict_ni = (
        all(delta >= NONINF_MARGIN for delta in per_seed)
        and ci[0] > NONINF_MARGIN
    )
    if all(delta > 0 for delta in per_seed) and ci[0] > 0:
        evidence = "REAL"
    elif all(delta < 0 for delta in per_seed) and ci[1] < 0:
        evidence = "NEGATIVE"
    elif mean_pooled > 0:
        evidence = "SUGGESTIVE"
    else:
        evidence = "NONE"
    return {
        "control": control,
        "treatment": treatment,
        "per_seed": dict(zip(map(str, SEEDS), per_seed)),
        "mean_pooled_delta": mean_pooled,
        "delta_f1_2": delta_f1_2,
        "delta_osd": delta_osd,
        "bootstrap": {
            "unit": "recording",
            "seeds_averaged_within_recording": True,
            "n_boot": N_BOOT,
            "rng_seed": BOOT_SEED,
            "mean_delta": float(per_recording_delta.mean()),
            "ci95": ci,
            "n_improved": int((per_recording_delta > 0).sum()),
            "n_recordings": len(recordings),
        },
        "evidence": evidence,
        "operational_mean_only_noninferior": operational_ni,
        "strict_noninferior": strict_ni,
        "practical_r2": practical_r2,
        "practical_r3": practical_r3,
        "practical_adoption": practical_r2 or practical_r3,
    }


def decide(primary: Mapping[str, Any]) -> Dict[str, Any]:
    if primary["operational_mean_only_noninferior"] and primary["practical_adoption"]:
        recommendation = "pre012"
        reason = (
            "pre012 passes operational NI and R2/R3 on the pyramid family; "
            "recommend stack_input_mask [1,1,1,0,0,0] in the chain base "
            "before sealing the root (requires explicit approval)"
        )
    elif primary["strict_noninferior"]:
        recommendation = "all6"
        reason = (
            "pre012 is strict-NI but passes neither R2 nor R3; "
            "non-inferiority alone does not justify changing the chain base"
        )
    else:
        recommendation = "all6"
        reason = (
            "pre012 does not transfer to the pyramid family; keep all6 and "
            "record the discordance with the TCN-family graduation result"
        )
    return {
        "chain_base_mask_recommendation": recommendation,
        "reason": reason,
        "phase8_base_mutated": False,
        "complexity_gate_reference": "immutable TCN root (unchanged)",
    }


def certified_result_lineage(snapshot: Mapping[str, Any]) -> Dict[str, Any]:
    lineage: Dict[str, Any] = {}
    for arm in ARMS:
        lineage[arm] = {}
        for seed in SEEDS:
            p = paths_for(arm, seed)
            config = make_config(arm, seed)
            wanted_yaml = canonical_yaml(config)
            wanted_inputs = protocol_inputs(config, snapshot)
            if not lineage_valid(arm, seed, wanted_yaml, wanted_inputs):
                fail(f"report refuses stale/uncertified arm: {tag(arm, seed)}")
            with p["sidecar"].open() as stream:
                sidecar = json.load(stream)
            live = output_fingerprint(arm, seed)
            if sidecar.get("outputs") != live:
                fail(f"report lineage drift: {tag(arm, seed)}")
            lineage[arm][str(seed)] = {
                "result": str(p["result"].relative_to(REPO)),
                "sidecar_sha": sha_file(p["sidecar"]),
                "outputs": live,
            }
    return lineage


def build_report() -> Dict[str, Any]:
    snapshot = source_snapshot()
    lineage = certified_result_lineage(snapshot)
    arm_rows = {
        arm: load_result_rows([paths_for(arm, seed)["result"] for seed in SEEDS])
        for arm in ARMS
    }
    primary = paired_stats(
        "all6", "pre012", arm_rows["all6"], arm_rows["pre012"]
    )
    # Descriptive only: level of the pyramid base against the immutable TCN
    # root.  The root arms predate this runner, so only their result files are
    # SHA-recorded here; no adoption rule reads this block.
    root_paths = [
        RESULTS / f"{ROOT_TAG}_s{seed}_voxsel.json" for seed in SEEDS
    ]
    descriptive = paired_stats(
        ROOT_TAG, "all6", load_result_rows(root_paths), arm_rows["all6"]
    )
    for key in (
        "operational_mean_only_noninferior", "strict_noninferior",
        "practical_r2", "practical_r3", "practical_adoption",
    ):
        descriptive.pop(key, None)
    descriptive["descriptive_only"] = True
    descriptive["root_result_shas"] = {
        str(seed): sha_file(path) for seed, path in zip(SEEDS, root_paths)
    }
    return {
        "protocol": "pyramid-mask-transfer-v1",
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "rules": {
            "noninferiority_margin": NONINF_MARGIN,
            "strict_noninferiority":
                "all seed deltas >= margin and bootstrap lower CI > margin",
            "r2": "mean pooled delta >= +0.005",
            "r3": "delta class-2 or OSD >= +0.010 and macro delta >= -0.002",
        },
        "comparisons": {
            "pre012_vs_all6_pyramid": primary,
            "pyramid_all6_vs_tcn_root": descriptive,
        },
        "decision": decide(primary),
        "source_snapshot": snapshot,
        "lineage": lineage,
    }


def print_report(report: Mapping[str, Any]) -> None:
    print("\n=== PYRAMID MASK TRANSFER: LOCKED STEP 3000 ===")
    primary = report["comparisons"]["pre012_vs_all6_pyramid"]
    ci = primary["bootstrap"]["ci95"]
    deltas = "/".join(f"{x:+.4f}" for x in primary["per_seed"].values())
    print(
        f"pre012_vs_all6(pyr)  seeds={deltas} "
        f"mean={primary['mean_pooled_delta']:+.4f} "
        f"bootCI=[{ci[0]:+.4f},{ci[1]:+.4f}] "
        f"opNI={primary['operational_mean_only_noninferior']} "
        f"strictNI={primary['strict_noninferior']} "
        f"adopt={primary['practical_adoption']} "
        f"evidence={primary['evidence']}"
    )
    descriptive = report["comparisons"]["pyramid_all6_vs_tcn_root"]
    d_ci = descriptive["bootstrap"]["ci95"]
    d_deltas = "/".join(f"{x:+.4f}" for x in descriptive["per_seed"].values())
    print(
        f"pyr_all6_vs_TCNroot  seeds={d_deltas} "
        f"mean={descriptive['mean_pooled_delta']:+.4f} "
        f"bootCI=[{d_ci[0]:+.4f},{d_ci[1]:+.4f}] (descriptive only)"
    )
    decision = report["decision"]
    print(
        "chain-base mask recommendation: "
        f"{decision['chain_base_mask_recommendation']} ({decision['reason']})"
    )
    print("Phase-8 base was not modified; the chain remains held.")


def acquire_lock() -> Any:
    ART.mkdir(parents=True, exist_ok=True)
    lock_path = ART / "runner.lock"
    lock = lock_path.open("a+")
    try:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        fail(f"another transfer runner holds {lock_path}")
    lock.seek(0)
    lock.truncate()
    lock.write(f"pid={os.getpid()} started={dt.datetime.now().isoformat()}\n")
    lock.flush()
    return lock


def preflight(
    require_runtime_capacity: bool,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    snapshot = source_snapshot()
    disk_preflight()
    if require_runtime_capacity:
        gpu_preflight()
    summary = validate_static_protocol(snapshot)
    print("Matched-model preflight passed:")
    for seed, row in summary.items():
        print(
            f"  seed {seed}: total={row['total_params']:,} "
            f"trainable={row['trainable_params']:,} "
            f"state={row['state_sha'][:12]} head={row['head_init_sha'][:12]}"
        )
    return snapshot, summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command", choices=("preflight", "run", "report"),
        help="training occurs only for the explicit 'run' command",
    )
    args = parser.parse_args()

    if args.command == "preflight":
        preflight(require_runtime_capacity=False)
        print("Preflight passed; no training or result artifact was created.")
        return

    lock = acquire_lock()
    _process_lock = lock
    if args.command == "run":
        snapshot, summary = preflight(require_runtime_capacity=True)
        RESULTS.mkdir(parents=True, exist_ok=True)
        LOGS.mkdir(parents=True, exist_ok=True)
        install_protocol_record(current_protocol_record(snapshot, summary))
        for seed, arm in RUN_ORDER:
            run_one(arm, seed, snapshot)
        assert_source_snapshot(snapshot, "after all arms")
        report = build_report()
        atomic_json(ART / "final_report.json", report)
        print_report(report)
    else:
        report = build_report()
        atomic_json(ART / "final_report.json", report)
        print_report(report)
    assert _process_lock is not None


if __name__ == "__main__":
    main()
